/*
*  ## Please DO NOT edit this file!! ##
*  This file is auto-generated from the register source files.
*  Any modifications to this file will be LOST when it is re-generated.
*
*  ----------------------------------------------------------------
*  (c) Realtek Semiconductor Corp. 2008
*
*  This file is property of Realtek Semiconductor Corp.
*  All rights reserved.
*
*  Abstract: chip register definition and API of RTL8307H
*
*  ---------------------------------------------------------------- */

#ifndef __RTL8307H_TABLEFIELD_LIST_H__
#define __RTL8307H_TABLEFIELD_LIST_H__

/* Module: Table Access */
extern rtk_tableField_t RTL8307H_VLAN_FIELDS[];
extern rtk_tableField_t RTL8307H_VLAN_CAM_FIELDS[];
extern rtk_tableField_t RTL8307H_L2_TABLE_FIELDS[];
extern rtk_tableField_t RTL8307H_LUT_BCAM_FIELDS[];
extern rtk_tableField_t RTL8307H_ACTION_TABLE_FIELDS[];
extern rtk_tableField_t RTL8307H_ACL_COUNTER_FIELDS[];
extern rtk_tableField_t RTL8307H_POLICER_FIELDS[];
extern rtk_tableField_t RTL8307H_PIE_TABLE_FIELDS[];
extern rtk_tableField_t RTL8307H_GROUP_FIELDS[];

#endif    /* __RTL8307H_TABLEFIELD_LIST_H__ */
