/*
*  ## Please DO NOT edit this file!! ##
*  This file is auto-generated from the register source files.
*  Any modifications to this file will be LOST when it is re-generated.
*
*  ----------------------------------------------------------------
*  (c) Realtek Semiconductor Corp. 2008
*
*  This file is property of Realtek Semiconductor Corp.
*  All rights reserved.
*
*  Abstract: chip register definition and API of RTL8307H
*
*  ---------------------------------------------------------------- */

#include <rtk_types.h>
#include <rtk_error.h>

#include "rtl8307h_table_struct.h"

/* Module: Table Access */
rtk_tableField_t RTL8307H_VLAN_FIELDS[] = 
{
    {   /* name     VLAN_MBR */
        /* lsp */   22,
        /* len */   8,
    },
    {   /* name     VLAN_UTAG */
        /* lsp */   14,
        /* len */   8,
    },
    {   /* name     VLAN_FID */
        /* lsp */   10,
        /* len */   4,
    },
    {   /* name     VLAN_ULFID */
        /* lsp */   9,
        /* len */   1,
    },
    {   /* name     VLAN_VLAN_BASE_FWD */
        /* lsp */   8,
        /* len */   1,
    },
    {   /* name     VLAN_VIDMSB */
        /* lsp */   1,
        /* len */   7,
    },
    {   /* name     VLAN_VALID */
        /* lsp */   0,
        /* len */   1,
    },
};

rtk_tableField_t RTL8307H_VLAN_CAM_FIELDS[] = 
{
    {   /* name     VLAN_CAM_UTAG */
        /* lsp */   51,
        /* len */   8,
    },
    {   /* name     VLAN_CAM_FID */
        /* lsp */   47,
        /* len */   4,
    },
    {   /* name     VLAN_CAM_ULFID */
        /* lsp */   46,
        /* len */   1,
    },
    {   /* name     VLAN_CAM_VLAN_BASE_FWD */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     VLAN_CAM_VID */
        /* lsp */   33,
        /* len */   12,
    },
    {   /* name     VLAN_CAM_VALID */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     VLAN_CAM_MBR */
        /* lsp */   0,
        /* len */   8,
    },
};

rtk_tableField_t RTL8307H_L2_TABLE_FIELDS[] = 
{
    {   /* name     L2_TABLE_L3ENTRY */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     L2_TABLE_AGE */
        /* lsp */   79,
        /* len */   2,
    },
    {   /* name     L2_TABLE_SPA */
        /* lsp */   76,
        /* len */   3,
    },
    {   /* name     L2_TABLE_SABLOCK */
        /* lsp */   75,
        /* len */   1,
    },
    {   /* name     L2_TABLE_DABLOCK */
        /* lsp */   74,
        /* len */   1,
    },
    {   /* name     L2_TABLE_AUTHIX */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     L2_TABLE_STATIC */
        /* lsp */   72,
        /* len */   1,
    },
    {   /* name     L2_TABLE_FID */
        /* lsp */   68,
        /* len */   4,
    },
    {   /* name     L2_TABLE_EAVPRI */
        /* lsp */   65,
        /* len */   3,
    },
    {   /* name     L2_TABLE_EAVPRIEN */
        /* lsp */   64,
        /* len */   1,
    },
    {   /* name     L2_TABLE_MAC_ADDRESS_40_9 */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     L2_TABLE_CVID_FID */
        /* lsp */   7,
        /* len */   12,
    },
    {   /* name     L2_TABLE_MAC_ADDRESS_47_41 */
        /* lsp */   0,
        /* len */   7,
    },
};

rtk_tableField_t RTL8307H_LUT_BCAM_FIELDS[] = 
{
    {   /* name     LUT_BCAM_L3ENTRY */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     LUT_BCAM_AGE */
        /* lsp */   79,
        /* len */   2,
    },
    {   /* name     LUT_BCAM_SPA */
        /* lsp */   76,
        /* len */   3,
    },
    {   /* name     LUT_BCAM_SABLOCK */
        /* lsp */   75,
        /* len */   1,
    },
    {   /* name     LUT_BCAM_DABLOCK */
        /* lsp */   74,
        /* len */   1,
    },
    {   /* name     LUT_BCAM_AUTHIX */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     LUT_BCAM_STATIC */
        /* lsp */   72,
        /* len */   1,
    },
    {   /* name     LUT_BCAM_FID */
        /* lsp */   68,
        /* len */   4,
    },
    {   /* name     LUT_BCAM_EAVPRI */
        /* lsp */   65,
        /* len */   3,
    },
    {   /* name     LUT_BCAM_EAVPRIEN */
        /* lsp */   64,
        /* len */   1,
    },
    {   /* name     LUT_BCAM_MAC_ADDRESS_31_0 */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     LUT_BCAM_CVID_FID */
        /* lsp */   16,
        /* len */   12,
    },
    {   /* name     LUT_BCAM_MAC_ADDRESS_47_32 */
        /* lsp */   0,
        /* len */   16,
    },
};

rtk_tableField_t RTL8307H_ACTION_TABLE_FIELDS[] = 
{
    {   /* name     ACTION_TABLE_FNO */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_DROP */
        /* lsp */   125,
        /* len */   2,
    },
    {   /* name     ACTION_TABLE_CP2CPU */
        /* lsp */   124,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_MIRROR */
        /* lsp */   123,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_OTAG */
        /* lsp */   122,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_ITAG */
        /* lsp */   121,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_PRIRMK */
        /* lsp */   120,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_REDIR */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_DSCPRMK */
        /* lsp */   118,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_PRIORITY */
        /* lsp */   117,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_BYRATELMT */
        /* lsp */   116,
        /* len */   1,
    },
    {   /* name     ACTION_TABLE_AIF1 */
        /* lsp */   79,
        /* len */   17,
    },
    {   /* name     ACTION_TABLE_AIF2 */
        /* lsp */   47,
        /* len */   17,
    },
    {   /* name     ACTION_TABLE_AIF3 */
        /* lsp */   21,
        /* len */   11,
    },
};

rtk_tableField_t RTL8307H_ACL_COUNTER_FIELDS[] = 
{
    {   /* name     ACL_COUNTER_TYPE */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     ACL_COUNTER_CNTMODE */
        /* lsp */   42,
        /* len */   1,
    },
    {   /* name     ACL_COUNTER_COUNTER */
        /* lsp */   0,
        /* len */   42,
    },
};

rtk_tableField_t RTL8307H_POLICER_FIELDS[] = 
{
    {   /* name     POLICER_TYPE */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     POLICER_TOKEN_COUNTER */
        /* lsp */   40,
        /* len */   18,
    },
    {   /* name     POLICER_THRESHOLD */
        /* lsp */   32,
        /* len */   8,
    },
    {   /* name     POLICER_RATE */
        /* lsp */   0,
        /* len */   16,
    },
};

rtk_tableField_t RTL8307H_PIE_TABLE_FIELDS[] = 
{
    {   /* name     PIE_TABLE_DATA_FIELD1 */
        /* lsp */   304,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD0 */
        /* lsp */   288,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD3 */
        /* lsp */   272,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD2 */
        /* lsp */   256,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD5 */
        /* lsp */   240,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD4 */
        /* lsp */   224,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD7 */
        /* lsp */   208,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_DATA_FIELD6 */
        /* lsp */   192,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_VALID */
        /* lsp */   176,
        /* len */   1,
    },
    {   /* name     PIE_TABLE_DATA_FIELD8 */
        /* lsp */   160,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD1 */
        /* lsp */   144,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD0 */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD3 */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD2 */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD5 */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD4 */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD7 */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD6 */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     PIE_TABLE_CARE_FIELD8 */
        /* lsp */   0,
        /* len */   16,
    },
};

rtk_tableField_t RTL8307H_GROUP_FIELDS[] = 
{
    {   /* name     GROUP_GROUP_IP */
        /* lsp */   32,
        /* len */   28,
    },
    {   /* name     GROUP_PORT_MASK */
        /* lsp */   0,
        /* len */   8,
    },
};

