/*
*  ## Please DO NOT edit this file!! ##
*  This file is auto-generated from the register source files.
*  Any modifications to this file will be LOST when it is re-generated.
*
*  ----------------------------------------------------------------
*  (c) Realtek Semiconductor Corp. 2008
*
*  This file is property of Realtek Semiconductor Corp.
*  All rights reserved.
*
*  Abstract: chip register definition and API of RTL8307H
*
*  ---------------------------------------------------------------- */

#ifndef __RTL8307H_REGFIELD_LIST_H__
#define __RTL8307H_REGFIELD_LIST_H__


/* Module: Table Access */
extern rtk_regField_t INDIRECT_CONTROL_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA0_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA1_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA2_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA3_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA4_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA5_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA6_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA7_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA8_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA9_FOR_8051_FIELDS[]; 
extern rtk_regField_t INDIRECT_OCCUPY_STATUS_FIELDS[]; 
extern rtk_regField_t INDIRECT_CONTROL_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA0_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA1_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA2_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA3_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA4_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA5_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA6_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA7_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA8_FOR_CPU_FIELDS[]; 
extern rtk_regField_t INDIRECT_DATA9_FOR_CPU_FIELDS[]; 
extern rtk_regField_t BURST_OPERATION_FIELDS[]; 
extern rtk_regField_t ALE_DMY0_FIELDS[]; 
extern rtk_regField_t ALE_DMY1_FIELDS[]; 
extern rtk_regField_t ALE_DMY2_FIELDS[]; 
extern rtk_regField_t ALE_DMY3_FIELDS[]; 
extern rtk_regField_t ALE_DMY4_FIELDS[]; 
extern rtk_regField_t ALE_DMY5_FIELDS[]; 
extern rtk_regField_t ALE_DMY6_FIELDS[]; 
extern rtk_regField_t ALE_DMY7_FIELDS[]; 
extern rtk_regField_t ALE_DMY8_FIELDS[]; 
extern rtk_regField_t ALE_DMY9_FIELDS[]; 

/* Module: Interface */
extern rtk_regField_t GLOBAL_MAC_INTERFACE_CONTROL0_FIELDS[]; 
extern rtk_regField_t GLOBAL_MAC_INTERFACE_INTERNAL1_FIELDS[]; 

/* Module: Reset */
extern rtk_regField_t RESET_GLOBAL_CONTROL0_FIELDS[]; 
extern rtk_regField_t RESET_GLOBAL_CONTROL1_FIELDS[]; 
extern rtk_regField_t RESET_GLOBAL_CONTROL2_FIELDS[]; 
extern rtk_regField_t RESET_GLOBAL_STATUS_FIELDS[]; 
extern rtk_regField_t RESET_DMY_FIELDS[]; 

/* Module: SMI */
extern rtk_regField_t PORT0_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT1_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT2_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT3_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT4_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT5_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT6_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT7_PROPERTY_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT0_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT1_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT2_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT3_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT4_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT5_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT6_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t PORT7_LINK_STATUS_FIELDS[]; 
extern rtk_regField_t SMI_CONTROL_FIELDS[]; 
extern rtk_regField_t PHY_REG_ACCESS_CONTROL0_FIELDS[]; 
extern rtk_regField_t PHY_REG_ACCESS_CONTROL1_FIELDS[]; 
extern rtk_regField_t PHY_AUTO_ACCESS_MASK_FIELDS[]; 
extern rtk_regField_t SMI_DMY_FIELDS[]; 

/* Module: I2C */
extern rtk_regField_t EXTERNAL_ACCESS_CONTROL_FIELDS[]; 
extern rtk_regField_t I2C_EXTERNAL_ACCESS_STATUS_FIELDS[]; 
extern rtk_regField_t I2C_EXTERNAL_ACCESS_ADDRESS_FIELDS[]; 
extern rtk_regField_t EEPROM_AUTO_DOWNLOAD_CONTROL_FIELDS[]; 
extern rtk_regField_t EEPROM_CODE_SIZE_ADDR_FIELDS[]; 
extern rtk_regField_t EEPROM_AUTODOWNLOAD_MAC_POSTION_FIELDS[]; 
extern rtk_regField_t EEPROM_AUTODOWNLOAD_PHY_POSTION_FIELDS[]; 
extern rtk_regField_t EEPROM_AUTODOWNLOAD_LUT_POSTION_FIELDS[]; 
extern rtk_regField_t EEPROM_STATUS__FIELDS[]; 
extern rtk_regField_t CPU_INDIRECT_ACCESS_EEPROM_CONTROL_FIELDS[]; 
extern rtk_regField_t CPU_INDIRECT_ACCESS_EEPROM_DATA0_FIELDS[]; 
extern rtk_regField_t CPU_INDIRECT_ACCESS_EEPROM_DATA1_FIELDS[]; 
extern rtk_regField_t I2C_OCCUPY_STATUS_FIELDS[]; 
extern rtk_regField_t I2C_DMY_FIELDS[]; 

/* Module: Hardware Misc */
extern rtk_regField_t IO_DRIVING_ABILITY_CONTROL0_FIELDS[]; 
extern rtk_regField_t IO_DRIVING_ABILITY_CONTROL1_FIELDS[]; 
extern rtk_regField_t IO_DRIVING_ABILITY_CONTROL2_FIELDS[]; 
extern rtk_regField_t IO_DRIVING_ABILITY_CONTROL3_FIELDS[]; 
extern rtk_regField_t IO_SLEW_RATE_CONTROL0_FIELDS[]; 
extern rtk_regField_t IO_SLEW_RATE_CONTROL1_FIELDS[]; 
extern rtk_regField_t IO_SLEW_RATE_CONTROL2_FIELDS[]; 
extern rtk_regField_t IO_SLEW_RATE_CONTROL3_FIELDS[]; 
extern rtk_regField_t HARDWARE_MISC_FIELDS[]; 
extern rtk_regField_t DGL_DEBUG0_FIELDS[]; 
extern rtk_regField_t DGL_DEBUG1_FIELDS[]; 
extern rtk_regField_t INTERNAL_BONDING_DEBUG_FIELDS[]; 
extern rtk_regField_t INTERNAL_STRAPPING_DEBUG0_FIELDS[]; 
extern rtk_regField_t INTERNAL_READ_FIELDS[]; 
extern rtk_regField_t BIAS_CONTROL_FIELDS[]; 
extern rtk_regField_t POWER_SAVING_CONTROL0_FIELDS[]; 
extern rtk_regField_t POWER_SAVING_CONTROL1_FIELDS[]; 
extern rtk_regField_t GPHY_GPIO_FIELDS[]; 
extern rtk_regField_t DEBUG0_FIELDS[]; 
extern rtk_regField_t DEBUG1_FIELDS[]; 
extern rtk_regField_t DEBUG2_FIELDS[]; 
extern rtk_regField_t DEBUG3_FIELDS[]; 
extern rtk_regField_t DEBUG4_FIELDS[]; 
extern rtk_regField_t DEBUG5_FIELDS[]; 
extern rtk_regField_t DEBUG6_FIELDS[]; 
extern rtk_regField_t DEBUG7_FIELDS[]; 

/* Module: BIST */
extern rtk_regField_t BIST_RESULT0_FIELDS[]; 
extern rtk_regField_t BIST_RESULT1_FIELDS[]; 
extern rtk_regField_t BIST_RESULT2_FIELDS[]; 
extern rtk_regField_t BIST_RESULT3_FIELDS[]; 
extern rtk_regField_t BIST_RESULT4_FIELDS[]; 
extern rtk_regField_t BIST_RESULT5_FIELDS[]; 
extern rtk_regField_t BIST_RESULT6_FIELDS[]; 
extern rtk_regField_t BIST_RESULT7_FIELDS[]; 
extern rtk_regField_t BIST_RESULT8_FIELDS[]; 
extern rtk_regField_t BIST_RESULT9_FIELDS[]; 
extern rtk_regField_t BIST_RESULT10_FIELDS[]; 
extern rtk_regField_t BIST_CONTROL_FIELDS[]; 

/* Module: Chip Version */
extern rtk_regField_t MODEL_REVISION_INFORMATION_FIELDS[]; 
extern rtk_regField_t MODEL_NAME_INFORMATION_REGSITER_FIELDS[]; 
extern rtk_regField_t CHIP_VERSION_ID_FIELDS[]; 

/* Module: EFUSE */
extern rtk_regField_t EFUSE_DEBUG_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA0_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA1_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA2_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA3_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA4_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA5_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA6_FIELDS[]; 
extern rtk_regField_t EFUSE_DATA7_FIELDS[]; 
extern rtk_regField_t EFUSE_BACKDOOR_FIELDS[]; 
extern rtk_regField_t DIRECT_MAPPING_RCODE_AND_OFFSET_FIELDS[]; 

/* Module: Port_based VLAN */
extern rtk_regField_t PORT_VLAN_CONTROL_FIELDS[]; 

/* Module: VLAN Decision */
extern rtk_regField_t PORT_ACCEPT_FRAME_TYPE_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_IGNORE_VLAN_TAG_CONTROL_FIELDS[]; 

/* Module: VLAN Priority Extraction */
extern rtk_regField_t INNER_TAG_PRIORITY_MAP_CONTROL0_FIELDS[]; 
extern rtk_regField_t INNER_TAG_PRIORITY_MAP_CONTROL1_FIELDS[]; 
extern rtk_regField_t OUTER_TAG_PRIORITY_MAP_CONTROL0_FIELDS[]; 
extern rtk_regField_t OUTER_TAG_PRIORITY_MAP_CONTROL1_FIELDS[]; 
extern rtk_regField_t OUTER_TAG_PRIORITY_MAP_CONTROL2_FIELDS[]; 
extern rtk_regField_t OUTER_TAG_PRIORITY_MAP_CONTROL3_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL0_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL1_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL2_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL3_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL4_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL5_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL6_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL7_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL8_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL9_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL10_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL11_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL12_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL13_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL14_FIELDS[]; 
extern rtk_regField_t DSCP_PRIORITY_MAP_CONTROL15_FIELDS[]; 
extern rtk_regField_t PRIORITY_ARBITRATION_CONTROL0_FIELDS[]; 
extern rtk_regField_t PRIORITY_ARBITRATION_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_PRIORITY_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_RX_PRIORITY_COPY_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDS[]; 

/* Module: VLAN Table Lookup and Tag Status */
extern rtk_regField_t VLAN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_VLAN_INGRESS_FILTER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_FORWARDING_TAG_SELECT_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_EGRESS_TAG_STATUS_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_VLAN_EGRESS_FILTER_CONTROL_FIELDS[]; 

/* Module: L2 Misc */
extern rtk_regField_t GLOBAL_MAC_L2_MISC0_FIELDS[]; 
extern rtk_regField_t PORT_L2_MISC_FIELDS[]; 

/* Module: Address Table Lookup */
extern rtk_regField_t ADDRESS_TABLE_LOOKUP_CONTROL_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_LOOKUP_MISS_CONTROL_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_MULTICAST_CONTROL0_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_MULTICAST_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_SOURCE_PORT_FILTER_FIELDS[]; 

/* Module: Spanning Tree */
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL0_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL1_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL2_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL3_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL4_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL5_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL6_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL7_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL8_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL9_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL10_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL11_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL12_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL13_FIELDS[]; 
extern rtk_regField_t SPANNING_TREE_PORT_STATE_CONTROL14_FIELDS[]; 
extern rtk_regField_t RSTP_GLOBAL_FIELDS[]; 
extern rtk_regField_t RSTP_PORT0_FIELDS[]; 
extern rtk_regField_t RSTP_PORT1_FIELDS[]; 
extern rtk_regField_t RSTP_PORT2_FIELDS[]; 
extern rtk_regField_t RSTP_PORT3_FIELDS[]; 

/* Module: Source MAC Learning */
extern rtk_regField_t SOURCE_MAC_LEARNING_CONTROL_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_FLUSH_CONTROL0_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_FLUSH_CONTROL1_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_SEARCH_CONTROL0_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_SEARCH_CONTROL1_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_SEARCH_CONTROL2_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_SEARCH_CONTROL3_FIELDS[]; 
extern rtk_regField_t ADDRESS_TABLE_SEARCH_RESULT_FIELDS[]; 

/* Module: Dot1x */
extern rtk_regField_t GUEST_VLAN_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t DOT1X_NETWORK_ACCESS_RELATED_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_BASED_DOT1X_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_EGRESS_DOT1X_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_MAC_BASED_DOT1X_CONTROL_FIELDS[]; 

/* Module: L2 Entry Number Constrain */
extern rtk_regField_t MAC_ADDRESS_NUMBER_CONSTRAIN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_SOURCE_MAC_LEARNING_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_MAC_LIMIT_CONTROL_FIELDS[]; 

/* Module: Attack Prevention */
extern rtk_regField_t ATTACK_PREVENTION_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t DOS_LENGTH_GLOBAL_CONTROL0_FIELDS[]; 
extern rtk_regField_t DOS_LENGTH_GLOBAL_CONTROL1_FIELDS[]; 

/* Module: Storm Control */
extern rtk_regField_t TRAFFSTORM_SUPPRESS_BYPASS_FIELDS[]; 
extern rtk_regField_t TRAFFSTORM_SUPPRESS_GLOBAL_FIELDS[]; 
extern rtk_regField_t TRAFFSTORM_SUPPRESS_TICK_TOKEN_FORBYTE_FIELDS[]; 
extern rtk_regField_t TRAFFSTORM_SUPPRESS_TICK_TOKEN_FORPPS_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_BROADCAST_RATE_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_BROADCAST_STATUS_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_BROADCAST_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_MULTICAST_RATE_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_MULTICAST_STATUS_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_MULTICAST_CONFIGURE_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_UNKNOWN_UNICAST_RATE_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_UNKNOWN_UNICAST_STATUS_FIELDS[]; 
extern rtk_regField_t PORT_TRAFFSTORM_SUPPRESS_UNKNOWN_UNICAST_CONFIGURE_FIELDS[]; 

/* Module: Port Isolation */
extern rtk_regField_t CPU_PORT_SELF_FILTERING_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_PORT_ISOLATION_CONTROL_FIELDS[]; 

/* Module: EEE MAC Control */
extern rtk_regField_t GLOBAL_EEE_MAC_CONTROL0_FIELDS[]; 
extern rtk_regField_t GLOBAL_EEE_MAC_CONTROL1_FIELDS[]; 
extern rtk_regField_t GLOBAL_EEE_MAC_CONTROL2_FIELDS[]; 
extern rtk_regField_t GLOBAL_EEE_MAC_CONTROL3_FIELDS[]; 
extern rtk_regField_t GLOBAL_EEE_MAC_CONTROL4_FIELDS[]; 
extern rtk_regField_t PORT0_HEAC_EEE_AUTO_NEGOTIATION_FIELDS[]; 
extern rtk_regField_t PORT1_HEAC_EEE_AUTO_NEGOTIATION_FIELDS[]; 
extern rtk_regField_t PORT2_HEAC_EEE_AUTO_NEGOTIATION_FIELDS[]; 
extern rtk_regField_t PORT3_HEAC_EEE_AUTO_NEGOTIATION_FIELDS[]; 
extern rtk_regField_t PORT6_HEAC_EEE_AUTO_NEGOTIATION_FIELDS[]; 
extern rtk_regField_t HEAC_NWAY_FRAME_BITS_DEFINITION_FIELDS[]; 
extern rtk_regField_t PORT0_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT1_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT2_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT3_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT6_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT0_HEAC_EEE_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT1_HEAC_EEE_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT2_HEAC_EEE_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT3_HEAC_EEE_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t PORT6_HEAC_EEE_LP_ADVERTISEMENT_FIELDS[]; 
extern rtk_regField_t EEE_DMY0_FIELDS[]; 
extern rtk_regField_t EEE_DMY1_FIELDS[]; 
extern rtk_regField_t EEE_DMY2_FIELDS[]; 
extern rtk_regField_t EEE_DMY3_FIELDS[]; 
extern rtk_regField_t PORT_EEE_MAC_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_LPI_INDICATION_COUNTER0_FIELDS[]; 
extern rtk_regField_t PORT_LPI_INDICATION_COUNTER1_FIELDS[]; 
extern rtk_regField_t PORT_LPI_INDICATION_COUNTER2_FIELDS[]; 
extern rtk_regField_t PORT_LINK_DOWN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_EEE_PORT_DMY0_FIELDS[]; 
extern rtk_regField_t PORT_EEE_PORT_DMY1_FIELDS[]; 
extern rtk_regField_t PORT_EEE_PORT_DMY2_FIELDS[]; 
extern rtk_regField_t PORT_EEE_PORT_DMY3_FIELDS[]; 

/* Module: Range Check */
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY0_0_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY0_1_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY1_0_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY1_1_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY2_0_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY2_1_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY3_0_FIELDS[]; 
extern rtk_regField_t L4PORT_RANGE_CHECKING_TABLE_ENTRY3_1_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY0_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY1_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY2_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY3_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY4_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY5_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY6_FIELDS[]; 
extern rtk_regField_t VID_RANGE_CHECKING_TABLE_ENTRY7_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY0_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY0_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY0_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY1_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY1_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY1_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY2_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY2_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY2_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY3_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY3_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY3_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY4_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY4_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY4_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY5_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY5_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY5_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY6_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY6_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY6_2_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY7_0_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY7_1_FIELDS[]; 
extern rtk_regField_t IP_RANGE_CHECKING_TABLE_ENTRY7_2_FIELDS[]; 
extern rtk_regField_t SOURCE_PORT_MASK_TABLE_ENTRY0_FIELDS[]; 
extern rtk_regField_t SOURCE_PORT_MASK_TABLE_ENTRY1_FIELDS[]; 
extern rtk_regField_t SOURCE_PORT_MASK_TABLE_ENTRY2_FIELDS[]; 
extern rtk_regField_t SOURCE_PORT_MASK_TABLE_ENTRY3_FIELDS[]; 
extern rtk_regField_t PACKET_LENGTH_RANGE_CHECKING_TABLE_ENTRY0_FIELDS[]; 
extern rtk_regField_t PACKET_LENGTH_RANGE_CHECKING_TABLE_ENTRY1_FIELDS[]; 
extern rtk_regField_t PACKET_LENGTH_RANGE_CHECKING_TABLE_ENTRY2_FIELDS[]; 
extern rtk_regField_t PACKET_LENGTH_RANGE_CHECKING_TABLE_ENTRY3_FIELDS[]; 

/* Module: PIE Lookup and Template Genarator */
extern rtk_regField_t USER_DEFINED_TEMPLATE_CONTROL0_FIELDS[]; 
extern rtk_regField_t USER_DEFINED_TEMPLATE_CONTROL1_FIELDS[]; 
extern rtk_regField_t USER_DEFINED_TEMPLATE_CONTROL2_FIELDS[]; 
extern rtk_regField_t USER_DEFINED_TEMPLATE_CONTROL3_FIELDS[]; 
extern rtk_regField_t PIE_RESULT_REVERSE_CONTROL0_FIELDS[]; 
extern rtk_regField_t PIE_RESULT_REVERSE_CONTROL1_FIELDS[]; 
extern rtk_regField_t PIE_BLOCK_PRIORITY_CONTROL_FIELDS[]; 
extern rtk_regField_t PIE_RESULT_AGGREGATOR_CONTROL0_FIELDS[]; 
extern rtk_regField_t PIE_RESULT_AGGREGATOR_CONTROL1_FIELDS[]; 
extern rtk_regField_t CLEAR_ACL_CONTENT_CONTROL_FIELDS[]; 

/* Module: ACL */
extern rtk_regField_t POLICER_TABLE_CONTROL_FIELDS[]; 
extern rtk_regField_t CRC_ERROR_FRAME_LOOKUP_CONTROL_FIELDS[]; 
extern rtk_regField_t ACL_COPYTOCPU_CONTROL_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_CONTROL0_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_CONTROL1_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_CONTROL2_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_CONTROL3_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_STATUS0_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_STATUS1_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_STATUS2_FIELDS[]; 
extern rtk_regField_t ACL_RULE_HIT_INTERRUPT_STATUS3_FIELDS[]; 
extern rtk_regField_t PORT_ACL_LOOKUP_CONTROL_FIELDS[]; 

/* Module: Flow Control */
extern rtk_regField_t FLOW_CONTROL_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t SYSTEM_DROP_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PUBLIC_PAGE_RX_USED_HIGH_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PUBLIC_PAGE_RX_USED_LOW_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t FLOW_CONTROL_ENABLE_DROP_PACKET_NUMBER_CONTROL_FIELDS[]; 
extern rtk_regField_t FLOW_CONTROL_OFF_PUBLIC_PAGE_RX_USED_DROP_ON_THRESHOLD_FIELDS[]; 
extern rtk_regField_t FLOW_CONTROL_OFF_PUBLIC_PAGE_RX_USED_DROP_OFF_THRESHOLD_FIELDS[]; 
extern rtk_regField_t PORT_FLOW_CONTROL_ENABLE_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_FLOWCONTROL_TX_QUEUE_DROP_ENABLE_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_RX_PAGE_HIGH_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_RX_PAGE_LOW_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_RX_PAGE_GUARANTEE_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_DROP_PAGE_THRESHOLD_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_DROP_PAGE_THRESHOLD_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_DROP_ABILITY_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_FLOW_CONTROL_OFF_PORT_RX_DROP_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_FLOW_CONTROL_ABILITY_FORCE_MODE_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_RX_PAGE_DROP_HIGH_THRESHOLD_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_RX_PAGE_DROP_LOW_THRESHOLD_CONTROL_FIELDS[]; 

/* Module: Remarking */
extern rtk_regField_t INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_FIELDS[]; 
extern rtk_regField_t INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_FIELDS[]; 
extern rtk_regField_t OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_FIELDS[]; 
extern rtk_regField_t OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_FIELDS[]; 
extern rtk_regField_t DSCP_REMARKING_TABLE_CONTROL0_FIELDS[]; 
extern rtk_regField_t DSCP_REMARKING_TABLE_CONTROL1_FIELDS[]; 
extern rtk_regField_t DSCP_REMARKING_TABLE_CONTROL2_FIELDS[]; 
extern rtk_regField_t DSCP_REMARKING_TABLE_CONTROL3_FIELDS[]; 
extern rtk_regField_t PORT_PRIORITY_REMARKING_CONTROL_FIELDS[]; 

/* Module: Ingress and Egress Bandwidth Control */
extern rtk_regField_t INGRESS_BANDWIDTH_CONTROL_DROP_THRESHOLD_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_HIGH_LOW_THRESHOLD_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_RATE_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_HIGH_LOW_THRESHOLD_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_RATE_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_ALGORITHM_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_PACKET_LENGTH_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_PACKET_LENGTH_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_EBS_THRESHOLD_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_INGRESS_BANDWIDTH_EBS_THRESHOLD_CONTROL1_FIELDS[]; 

/* Module: Queue Management and Queue Schedule */
extern rtk_regField_t LEAKY_BUKET_SYSTEM_CONTROL_FIELDS[]; 
extern rtk_regField_t LEAKY_BUKET_SYSTEM_COUNTER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_LEAKY_BUKET_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_Q0_SCHEDULER_BUCKET_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_Q0_SCHEDULER_BUCKET_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_Q0_SCHEDULER_BUCKET_CONTROL2_FIELDS[]; 
extern rtk_regField_t PORT_Q1_SCHEDULER_BUCKET_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_Q1_SCHEDULER_BUCKET_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_Q1_SCHEDULER_BUCKET_CONTROL2_FIELDS[]; 
extern rtk_regField_t PORT_Q2_SCHEDULER_BUCKET_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_Q2_SCHEDULER_BUCKET_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_Q2_SCHEDULER_BUCKET_CONTROL2_FIELDS[]; 
extern rtk_regField_t PORT_Q3_SCHEDULER_BUCKET_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_Q3_SCHEDULER_BUCKET_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_Q3_SCHEDULER_BUCKET_CONTROL2_FIELDS[]; 
extern rtk_regField_t PORT_BANDWITH_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_BANDWITH_CURRENT_TOKEN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_SCHEDULE_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_0_PACKET_NUMBER_COUNTER_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_1_PACKET_NUMBER_COUNTER_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_2_PACKET_NUMBER_COUNTER_FIELDS[]; 
extern rtk_regField_t PORT_QUEUE_3_PACKET_NUMBER_COUNTER_FIELDS[]; 

/* Module: Mirroring */
extern rtk_regField_t TRAFFIC_MIRROR_CONTROL0_FIELDS[]; 
extern rtk_regField_t TRAFFIC_MIRROR_CONTROL1_FIELDS[]; 
extern rtk_regField_t TRAFFIC_MIRROR_CONTROL2_FIELDS[]; 
extern rtk_regField_t MIRROR_PORT_EGRESS_FILTER_CONTROL_FIELDS[]; 
extern rtk_regField_t TRAFFIC_MIRROR_SAMPLE_CONTROL_FIELDS[]; 
extern rtk_regField_t TRAFFIC_MIRROR_SAMPLE_STATISTIC_FIELDS[]; 

/* Module: Packet Parser */
extern rtk_regField_t CPU_TAG_CONTROL_FIELDS[]; 
extern rtk_regField_t PACKET_PARSER_PID_CONTROL_REGIST_FIELDS[]; 
extern rtk_regField_t PACKET_PARSER_LAYER2_TYPE_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_MAXLEN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT5_MAXLEN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT6_MAXLEN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT7_MAXLEN_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT0_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT1_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT2_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT3_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT4_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT5_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT6_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT7_PACKET_PARSER_CONTROL_FIELDS[]; 
extern rtk_regField_t SWITCH_OWN_IP_ADDRESS_FIELDS[]; 
extern rtk_regField_t PORT_CHECKSUM_ERROR_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_DROP_REASON_FIELDS[]; 

/* Module: ALE Misc */
extern rtk_regField_t IGMP_MLD_CONTROL_FIELDS[]; 
extern rtk_regField_t OPTION_HEADER_TRAP_CONTROL_FIELDS[]; 
extern rtk_regField_t CFI_CONTROL_FIELDS[]; 
extern rtk_regField_t ARP_CONTROL_FIELDS[]; 
extern rtk_regField_t IGMP_CONTROL_FIELDS[]; 

/* Module: RMA */
extern rtk_regField_t RMA_CONTROL0_FIELDS[]; 
extern rtk_regField_t RMA_CONTROL1_FIELDS[]; 
extern rtk_regField_t RMA_CONTROL2_FIELDS[]; 
extern rtk_regField_t RMA_CONTROL3_FIELDS[]; 
extern rtk_regField_t RMA_CONTROL4_FIELDS[]; 

/* Module: TX Modification */
extern rtk_regField_t CPU_PORT_TX_TAG_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_TX_TAG_CONTROL0_FIELDS[]; 
extern rtk_regField_t PORT_TX_TAG_CONTROL1_FIELDS[]; 
extern rtk_regField_t PORT_TX_TAG_CONTROL2_FIELDS[]; 

/* Module: CPU Releated */
extern rtk_regField_t CPU_8051_RESET_FIELDS[]; 
extern rtk_regField_t DMA_CONTROL_FIELDS[]; 
extern rtk_regField_t DESTINATION_MEMORY_ADDRESS_FIELDS[]; 
extern rtk_regField_t SOURCE_MEMORY_ADDRESS_FIELDS[]; 
extern rtk_regField_t DATA_LENGTH__FIELDS[]; 
extern rtk_regField_t CPU_FREQUENCY_FIELDS[]; 
extern rtk_regField_t INTERNAL_MEMORY_CONTROL_FIELDS[]; 
extern rtk_regField_t INTERNAL_MEMORY_DATA0_FIELDS[]; 
extern rtk_regField_t INTERNAL_MEMORY_DATA1_FIELDS[]; 
extern rtk_regField_t SWITCHACCESS_ADDRESS_FIELDS[]; 
extern rtk_regField_t SWITCHACCESS_DATA_FIELDS[]; 
extern rtk_regField_t SWITCHACCESS_CONTROL_FIELDS[]; 
extern rtk_regField_t IROM_ACCESS_ADDRESS_FIELDS[]; 
extern rtk_regField_t IROM_ACCESS_DATA_FIELDS[]; 
extern rtk_regField_t IROM_ACCESS_CONTROL_FIELDS[]; 
extern rtk_regField_t SPI_CONTROLLER_GLOBAL_FIELDS[]; 
extern rtk_regField_t SPI_RIMODE_CONTROL_FIELDS[]; 
extern rtk_regField_t SPI_SMODE_CONTROL_FIELDS[]; 
extern rtk_regField_t SPI_SMODE_ADDRESS_FIELDS[]; 
extern rtk_regField_t SPI_SMODE_DATA0_FIELDS[]; 
extern rtk_regField_t SPI_SMODE_DATA1_FIELDS[]; 
extern rtk_regField_t SPI_SMODE_DATA2_FIELDS[]; 
extern rtk_regField_t SPI_SMODE_DATA3_FIELDS[]; 
extern rtk_regField_t CPU_INTERRUPT_PS2LVL_FIELDS[]; 
extern rtk_regField_t WATCH_DOG_CONTROL_FIELDS[]; 
extern rtk_regField_t WATCH_DOG_THRESHOLD_FIELDS[]; 
extern rtk_regField_t WATCH_DOG_COUNTER_FIELDS[]; 

/* Module: RLDP */
extern rtk_regField_t RTKPP_RANDOM_NUMBER_CONTROL0_FIELDS[]; 
extern rtk_regField_t RTKPP_RANDOM_NUMBER_CONTROL1_FIELDS[]; 
extern rtk_regField_t RTKPP_RANDOM_NUMBER_CONTROL2_FIELDS[]; 
extern rtk_regField_t RLDP_LOOP_STATE_RETRY_CONTROL_FIELDS[]; 
extern rtk_regField_t RLDP_CHECK_STATE_RETRY_CONTROL_FIELDS[]; 
extern rtk_regField_t RLDP_ENABLE_PORT_MASK_CONTROL_FIELDS[]; 
extern rtk_regField_t RLDP_LOOP_PORT_MASK_CONTROL_FIELDS[]; 
extern rtk_regField_t RLDP_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t TX_DISABLE_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t RX_DISABLE_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT0_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t PORT1_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t PORT2_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t PORT3_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t PORT4_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t PORT5_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t PORT6_LOOP_PORT_FIELDS[]; 
extern rtk_regField_t SWITCH_OWN_MAC_CONTROL0_FIELDS[]; 
extern rtk_regField_t SWITCH_OWN_MAC_CONTROL1_FIELDS[]; 
extern rtk_regField_t EXTRA_PORT_DEBUG_CONTROL_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL0_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL1_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL2_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL3_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL4_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL5_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL6_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL7_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL8_FIELDS[]; 
extern rtk_regField_t SIMPLE_PACKET_GENERATOR_CONTROL9_FIELDS[]; 

/* Module: MIB Counter */
extern rtk_regField_t MIB_COUNTER_CONTROL0_FIELDS[]; 
extern rtk_regField_t MIB_COUNTER_CONTROL1_FIELDS[]; 
extern rtk_regField_t MIB_COUNTER_CONTROL2_FIELDS[]; 
extern rtk_regField_t INDIRECT_ACCESS_MIB_COUNTER_CONTROL_FIELDS[]; 
extern rtk_regField_t INDIRECT_ACCESS_MIB_COUNTER_DATA0_FIELDS[]; 
extern rtk_regField_t INDIRECT_ACCESS_MIB_COUNTER_DATA1_FIELDS[]; 
extern rtk_regField_t QUEUE_MIB_COUNTER_COUNT_TYPE_SELECTION_FIELDS[]; 
extern rtk_regField_t GLOBAL_MIB_COUNTER_OVERFLOW_FLAG_FIELDS[]; 
extern rtk_regField_t SYSTEM_MIB_COUNTER_OVERFLOW_FLAG_FIELDS[]; 
extern rtk_regField_t PORT0_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT0_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT1_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT1_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT2_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT2_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT3_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT3_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT4_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT4_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT5_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT5_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT6_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT6_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t PORT7_MIBCOUNTER_OVERFLOW_FLAG0_FIELDS[]; 
extern rtk_regField_t PORT7_MIBCOUNTER_OVERFLOW_FLAG1_FIELDS[]; 
extern rtk_regField_t TEST_MODE_TRIGGER_FIELDS[]; 
extern rtk_regField_t TEST_MODE_WRITE_DATA0_FIELDS[]; 
extern rtk_regField_t TEST_MODE_WRITE_DATA1_FIELDS[]; 
extern rtk_regField_t TEST_MODE_READ_DATA0_FIELDS[]; 
extern rtk_regField_t TEST_MODE_READ_DATA1_FIELDS[]; 

/* Module: GPIO */
extern rtk_regField_t GPIO_FUNCSELECT_DIRECTR_DATA_REG_FIELDS[]; 
extern rtk_regField_t GPIO_INT_STATUS_MASK_MODE_FIELDS[]; 

/* Module: Interrupt */
extern rtk_regField_t SWITCH_INTERRUPT_GLOBAL_CONTROL0_FIELDS[]; 
extern rtk_regField_t PACKET_DROP_INTERRUPT_CONTROL0_FIELDS[]; 
extern rtk_regField_t PACKET_DROP_INTERRUPT_CONTROL1_FIELDS[]; 
extern rtk_regField_t MISC_INTERRUPT_CONTROL_FIELDS[]; 
extern rtk_regField_t SWITCH_INTERRUPT_GLOBAL_SOURCE_STATUS_FIELDS[]; 
extern rtk_regField_t PACKET_DROP_INTERRUPT_STATUS0_FIELDS[]; 
extern rtk_regField_t PACKET_DROP_INTERRUPT_STATUS1_FIELDS[]; 
extern rtk_regField_t MISC_INTERRUPT_STATUS_FIELDS[]; 
extern rtk_regField_t SWITCH_INTERRUPT_MODE_8051EVENT_FIELDS[]; 
extern rtk_regField_t LINK_CHANGE_INTERRUPT_CONTROL_FIELDS[]; 
extern rtk_regField_t SA_LEARNING_CONSTRAIN_INTERRUPT_CONTROL_FIELDS[]; 
extern rtk_regField_t LINK_CHANGE_INTERRUPT_STATUS_FIELDS[]; 
extern rtk_regField_t SA_LEARNING_CONSTRAIN_INTERRUPT_STATUS_FIELDS[]; 

/* Module: WOL */
extern rtk_regField_t WOL_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t WOL_CONTROL_FIELDS[]; 
extern rtk_regField_t WPF_CRC_MATCH0_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK0_0_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK0_1_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK0_2_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK0_3_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK1_0_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK1_1_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK1_2_FIELDS[]; 
extern rtk_regField_t WAKEUP_FRAME_MASK1_3_FIELDS[]; 
extern rtk_regField_t LSB_NODE_ID_1_FIELDS[]; 
extern rtk_regField_t HSB_NODE_ID_1_FIELDS[]; 
extern rtk_regField_t LSB_NODE_ID_2_FIELDS[]; 
extern rtk_regField_t HSB_NODE_ID_2_FIELDS[]; 
extern rtk_regField_t LSB_NODE_ID_3_FIELDS[]; 
extern rtk_regField_t HSB_NODE_ID_3_FIELDS[]; 

/* Module: LED */
extern rtk_regField_t LED_CONTROL0_FIELDS[]; 
extern rtk_regField_t LED_STATUS_CONTROL0_FIELDS[]; 

/* Module: NIC */
extern rtk_regField_t NIC_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t TXSTOP_ADDRESS_FIELDS[]; 
extern rtk_regField_t RXSTOP_ADDRESS_FIELDS[]; 
extern rtk_regField_t RX_BUFFER_RECEIVED_DATA_LENGTH_FIELDS[]; 
extern rtk_regField_t TX_BUFFER_AVAILABLE_FREE_SPACE_FIELDS[]; 
extern rtk_regField_t RX_COMMAND_FIELDS[]; 
extern rtk_regField_t TX_COMMAND_FIELDS[]; 
extern rtk_regField_t NIC_INTERRUPT_STATUS_FIELDS[]; 
extern rtk_regField_t NIC_INTERRUPT_MASK_FIELDS[]; 
extern rtk_regField_t RX_CONTROL_FIELDS[]; 
extern rtk_regField_t TX_CONTROL_FIELDS[]; 
extern rtk_regField_t CPU_RX_CURRENT_PACKET_FIELDS[]; 
extern rtk_regField_t CPU_TX_CURRENT_PACKET_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH0_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH1_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH2_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH3_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH4_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH5_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH6_FIELDS[]; 
extern rtk_regField_t MULTICAST_HASH7_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH0_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH1_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH2_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH3_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH4_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH5_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH6_FIELDS[]; 
extern rtk_regField_t PHYSICAL_ADDRESS_HASH7_FIELDS[]; 
extern rtk_regField_t SRXCURPKTR_FIELDS[]; 
extern rtk_regField_t STXCURPKTR_FIELDS[]; 
extern rtk_regField_t TXPKTLENR_FIELDS[]; 
extern rtk_regField_t STXCURUNITR_FIELDS[]; 

/* Module: ALE Related Diagnostic */
extern rtk_regField_t ALE_TEST_MODE_CONTROL_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR0_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR1_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR2_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR3_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR4_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR5_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR6_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR7_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR8_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR9_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR10_FIELDS[]; 
extern rtk_regField_t HEADER_STAMP_BEFORE_CR11_FIELDS[]; 
extern rtk_regField_t PACKET_MODIFICATION_INFORMATION_CR0_FIELDS[]; 
extern rtk_regField_t PACKET_MODIFICATION_INFORMATION_CR1_FIELDS[]; 
extern rtk_regField_t PACKET_MODIFICATION_INFORMATION_CR2_FIELDS[]; 
extern rtk_regField_t PACKET_MODIFICATION_INFORMATION_CR3_FIELDS[]; 
extern rtk_regField_t PACKET_MODIFICATION_INFORMATION_CR4_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR0_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR1_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR2_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR3_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR4_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR5_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR6_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION0_CR7_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR0_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR1_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR2_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR3_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR4_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR5_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR6_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION1_CR7_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR0_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR1_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR2_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR3_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR4_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR5_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR6_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION2_CR7_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR0_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR1_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR2_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR3_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR4_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR5_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR6_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION3_CR7_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR0_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR1_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR2_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR3_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR4_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR5_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR6_FIELDS[]; 
extern rtk_regField_t PACKET_PROCESS_INFORMATION4_CR7_FIELDS[]; 

/* Module: Flow Control Diagnostic */
extern rtk_regField_t FLOWCTL_GLOBAL_PAGECNT_BEYOND_THRESHOLD_TIMES_FIELDS[]; 
extern rtk_regField_t GLOBAL_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDS[]; 
extern rtk_regField_t SYSTEM_PAGE_COUNTER_FIELDS[]; 
extern rtk_regField_t DEBUG_COUNTER_RESET_FIELDS[]; 
extern rtk_regField_t PORT_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDS[]; 
extern rtk_regField_t PORT_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDS[]; 
extern rtk_regField_t PORT_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDS[]; 

/* Module: MII Test Related Diagnostic */
extern rtk_regField_t MAC_MII_TEST_MODE_TX_CONTROL_FIELDS[]; 
extern rtk_regField_t MAC_MII_TEST_MODE_RX_CONTROL_FIELDS[]; 
extern rtk_regField_t MAC_TEST_MODE_GMII_RX_FIELDS[]; 
extern rtk_regField_t MAC_TEST_MODE_GMII_TX_FIELDS[]; 

/* Module: EAV */
extern rtk_regField_t EAV_GLOBAL_CONTROL_FIELDS[]; 
extern rtk_regField_t EAV_SYSTEM_TIME_FREQUENCY_CONTROL_FIELDS[]; 
extern rtk_regField_t EAV_SYSTEM_TIME_OFFSET_SECOND_CONTROL_FIELDS[]; 
extern rtk_regField_t EAV_SYSTEM_TIME_OFFSET_NEROSECOND_CONTROL_FIELDS[]; 
extern rtk_regField_t EAV_SYSTEM_TIME_SECOND_CONTROL_FIELDS[]; 
extern rtk_regField_t EAV_SYSTEM_TIME_NEROSECOND_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_EAV_CONTROL_FIELDS[]; 
extern rtk_regField_t PORT_PRECISE_ORIGIN_TIME_STAMP_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_PRECISE_ORIGIN_TIME_STAMP_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_SYNC_EGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_SYNC_EGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDREQ_EGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDREQ_EGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORTPDRESP_EGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDRESP_EGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_OTHER_EGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_OTHER_EGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_SYNC_INGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_SYNC_INGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDREQ_INGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDREQ_INGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDRESP_INGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_PDRESP_INGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_OTHER_INGRESS_SECOND_FIELDS[]; 
extern rtk_regField_t PORT_OTHER_INGRESS_NEROSECOND_FIELDS[]; 
extern rtk_regField_t PORT_PRIORITY_REGENARATION_MAPPING_TABLE_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q0_BUCKET_THRESHOLD_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q1_BUCKET_THRESHOLD_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q2_BUCKET_THRESHOLD_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q3_BUCKET_THRESHOLD_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q0_BUCKET_WEIGHT_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q1_BUCKET_WEIGHT_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q2_BUCKET_WEIGHT_FIELDS[]; 
extern rtk_regField_t PORT_EAV_SCHEDULE_Q3_BUCKET_WEIGHT_FIELDS[]; 
extern rtk_regField_t PORT_EAV_CONFIGURE_CHANGE_STATUS_FIELDS[]; 

/* Module: CEC */
extern rtk_regField_t CEC_CR0_FIELDS[]; 
extern rtk_regField_t CEC_RTCR0_FIELDS[]; 
extern rtk_regField_t CEC_RXCR0_FIELDS[]; 
extern rtk_regField_t CEC_TXCR0_FIELDS[]; 
extern rtk_regField_t CEC_TXDR0_FIELDS[]; 
extern rtk_regField_t CEC_TXDR1_FIELDS[]; 
extern rtk_regField_t CEC_TXDR2_FIELDS[]; 
extern rtk_regField_t CEC_TXDR3_FIELDS[]; 
extern rtk_regField_t CEC_TXDR4_FIELDS[]; 
extern rtk_regField_t CEC_RXDR1_FIELDS[]; 
extern rtk_regField_t CEC_RXDR2_FIELDS[]; 
extern rtk_regField_t CEC_RXDR3_FIELDS[]; 
extern rtk_regField_t CEC_RXDR4_FIELDS[]; 
extern rtk_regField_t CEC_RXTCR0_FIELDS[]; 
extern rtk_regField_t CEC_TXTCR0_FIELDS[]; 
extern rtk_regField_t CEC_TXTCR1_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_01_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPCODE_01_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPERAND_NUMBER_01_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_01_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_02_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_03_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_02_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPCODE_02_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPERAND_NUMBER_02_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_04_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_05_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_06_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_03_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPCODE_03_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPERAND_NUMBER_03_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_07_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_08_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_09_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_04_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPCODE_04_FIELDS[]; 
extern rtk_regField_t GDI_CEC_SEND_OPERAND_NUMBER_04_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_10_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_11_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPERAND_12_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_05_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_06_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_07_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_08_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_09_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_10_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_11_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_12_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_13_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_14_FIELDS[]; 
extern rtk_regField_t GDI_CEC_COMPARE_OPCODE_15_FIELDS[]; 
extern rtk_regField_t GDI_CEC_OPCODE_ENABLE_FIELDS[]; 
extern rtk_regField_t GDI_POWER_SAVING_MODE_FIELDS[]; 
extern rtk_regField_t CEC_ANALOG_01_FIELDS[]; 
#endif    /* __RTL8307H_REGFIELD_LIST_H__ */
