/*
*  ## Please DO NOT edit this file!! ##
*  This file is auto-generated from the register source files.
*  Any modifications to this file will be LOST when it is re-generated.
*
*  ----------------------------------------------------------------
*  (c) Realtek Semiconductor Corp. 2008
*
*  This file is property of Realtek Semiconductor Corp.
*  All rights reserved.
*
*  Abstract: chip register definition and API of RTL8307H
*
*  ---------------------------------------------------------------- */

#include <rtk_types.h>
#include <rtk_error.h>

#include "rtl8307h_reg_struct.h"
#include "rtl8307h_table_struct.h"
#include "rtl8307h_tableField_list.h"

#define INCR         INDIRECT_CONTROL_FOR_CPU
#define INCR_EXE     EXECUTE_CPU
#define INCR_RW      ACCMD_CPU
#define INCR_TYPE    ACCTBTP_CPU
#define INCR_ADDR    ACCADDR_CPU
#define INDR_BASE    INDIRECT_DATA0_FOR_CPU

int32 table_read(uint32 unit, rtk_table_list_t table, uint32 addr, uint32 *data)
{
    uint32 reg_data = 0;
    uint32 busy = 0;
    uint32 i;

    if ((table >= TABLE_LIST_END) || (addr >= rtl8307h_table_list[table].size))
        return FAILED;

    reg_field_set(unit, INCR, INCR_EXE, 1, &reg_data);    /* 1 = EXECUTE */
    reg_field_set(unit, INCR, INCR_RW, 1, &reg_data);     /* 1 = READ */
    reg_field_set(unit, INCR, INCR_TYPE, rtl8307h_table_list[table].type, &reg_data);
    reg_field_set(unit, INCR, INCR_ADDR, addr, &reg_data);
    reg_write(unit, INCR, reg_data);

    do {
        reg_field_read(unit, INCR, INCR_EXE, &busy);
    } while (busy);

    for (i=0; i<rtl8307h_table_list[table].datareg_num; i++)
    {
        reg_read(unit, INDR_BASE+i, data+i);
    }

    return SUCCESS;
}

int32 table_write(uint32 unit, rtk_table_list_t table, uint32 addr, uint32 *data)
{
    uint32 reg_data = 0;
    uint32 busy = 0;
    uint32 i;

    if ((table >= TABLE_LIST_END) || (addr >= rtl8307h_table_list[table].size))
        return FAILED;

    for (i=0; i<rtl8307h_table_list[table].datareg_num; i++)
    {
        reg_write(unit, INDR_BASE+i, *(data+i));
    }

    reg_field_set(unit, INCR, INCR_EXE, 1, &reg_data);    /* 1 = EXECUTE */
    reg_field_set(unit, INCR, INCR_RW, 0, &reg_data);     /* 0 = WRITE */
    reg_field_set(unit, INCR, INCR_TYPE, rtl8307h_table_list[table].type, &reg_data);
    reg_field_set(unit, INCR, INCR_ADDR, addr, &reg_data);
    reg_write(unit, INCR, reg_data);

    do {
        reg_field_read(unit, INCR, INCR_EXE, &busy);
    } while (busy);

    return SUCCESS;
}

rtk_table_t rtl8307h_table_list[] =
{
    {   /* table name               VLAN */
        /* access table type */     0,
        /* table size */            128,
        /* total data registers */  1,
        /* total field numbers */   7,
        /* table fields */          RTL8307H_VLAN_FIELDS
    },
    {   /* table name               VLAN_CAM */
        /* access table type */     1,
        /* table size */            16,
        /* total data registers */  2,
        /* total field numbers */   7,
        /* table fields */          RTL8307H_VLAN_CAM_FIELDS
    },
    {   /* table name               L2_TABLE */
        /* access table type */     2,
        /* table size */            2048,
        /* total data registers */  3,
        /* total field numbers */   13,
        /* table fields */          RTL8307H_L2_TABLE_FIELDS
    },
    {   /* table name               LUT_BCAM */
        /* access table type */     3,
        /* table size */            16,
        /* total data registers */  3,
        /* total field numbers */   13,
        /* table fields */          RTL8307H_LUT_BCAM_FIELDS
    },
    {   /* table name               ACTION_TABLE */
        /* access table type */     4,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   14,
        /* table fields */          RTL8307H_ACTION_TABLE_FIELDS
    },
    {   /* table name               ACL_COUNTER */
        /* access table type */     5,
        /* table size */            64,
        /* total data registers */  2,
        /* total field numbers */   3,
        /* table fields */          RTL8307H_ACL_COUNTER_FIELDS
    },
    {   /* table name               POLICER */
        /* access table type */     6,
        /* table size */            64,
        /* total data registers */  2,
        /* total field numbers */   4,
        /* table fields */          RTL8307H_POLICER_FIELDS
    },
    {   /* table name               PIE_TABLE */
        /* access table type */     7,
        /* table size */            128,
        /* total data registers */  10,
        /* total field numbers */   19,
        /* table fields */          RTL8307H_PIE_TABLE_FIELDS
    },
    {   /* table name               GROUP */
        /* access table type */     8,
        /* table size */            128,
        /* total data registers */  2,
        /* total field numbers */   2,
        /* table fields */          RTL8307H_GROUP_FIELDS
    },
};
