#ifndef _rtl8307h_TYPES_H_
#define _rtl8307h_TYPES_H_

#include <rtk_types.h>

#define CHK_FUN_RETVAL(f) \
do { \
        if (RT_ERR_OK != (f)) \
            return (RT_ERR_SMI); \
} while(0)

#define RTL8307H_UNIT                       1

enum RTL8307H_PORTNUM
{
    PN_PORT0 = 0,
    PN_PORT1,
    PN_PORT2,
    PN_PORT3,
    PN_PORT4,
    /*5~9*/
    PN_PORT5,
    PN_PORT6,
    PN_PORT7,
    PN_PORT_END,
};

enum PORT_MASK
{
    PM_PORT_0 = (1 << PN_PORT0),
    PM_PORT_1 = (1 << PN_PORT1),
    PM_PORT_2 = (1 << PN_PORT2),
    PM_PORT_3 = (1 << PN_PORT3),
    PM_PORT_4 = (1 << PN_PORT4),
    PM_PORT_5 = (1 << PN_PORT5),
    PM_PORT_6 = (1 << PN_PORT6),
    PM_PORT_7 = (1 << PN_PORT7),
    PM_PORT_ALL = 0xff,
};

#define IS_VALID_PORT_ID(portId)            (((portId) < PN_PORT_END ) ? 1 : 0)
#define IS_VALID_PORT_MASK(portMask)        (((portMask) & PM_PORT_ALL) ? 1 : 0)
#define IS_VALID_PHY_ID(phyId)              ((((phyId) == 4) || ((phyId) == 6)) ? 1 : 0)
#define IS_VALID_HEAC_PORT_ID(portId)       ((((portId) >= 0 && (portId) <= 3) || ((portId) == 6)) ? 1 : 0)


/* STP */
#define RTL8307H_MSTIMAX                    15  
#define RTL8307H_STP_BRIDGE_PORT_PRIORITYMAX    0xf
#define RTL8307H_STP_AGEMIN                 6
#define RTL8307H_STP_AGEMAX                 40
#define RTL8307H_STP_FORWARD_DELAYMIN       4
#define RTL8307H_STP_FORWARD_DELAYMAX       30
#define RTL8307H_STP_HELLOTIMEMIN           1
#define RTL8307H_STP_HELLOTIMEMAX           2

#define RTL8307H_STP_PATHCOSTMAX            0xf

/* QOS */
#define RTL8307H_INDEXMAX                   1

#define RTL8307H_QUEUENO                    4
#define RTL8307H_QIDMAX                     (RTL8307H_QUEUENO-1)

#define RTL8307H_PRIMAX                     7
#define RTL8307H_DEIMAX                     1
#define RTL8307H_PRIWEIGHTMAX               7
#define RTL8307H_DSCPMAX                    63

#define RTL8307H_PORTRATEMAX                0x1ffff
#define RTL8307H_WEIGHTMAX                  0x3f

#define RTL8307H_INGRESS_LEAKYBUCKETMAX     1

/* VLAN */
#define RTL8307H_VIDMAX                     0XFFF
#define RTL8307H_VLANCAMMAX                 16
#define RTL8307H_FIDMAX                     14
#define RTL8307H_VLAN_FLUSH_TIMEOUT         655535

/* the above macro is generated by genDotH */
#define RTL8307H_VALID_REG_NO               3236


#endif /* _rtl8307h_TYPES_H_ */
